### ISSUE TITLE
Make PhpStorm depends from org.freedesktop.Sdk.Extension.php83

### ISSUE THREAD

**Issue by xanscale** [flathub/com.jetbrains.PhpStorm#117]
https://docs.flatpak.org/en/latest/extension.html

this editor is useless without php extension, but actually need to be installed manually
it's possible to make phpstorm deprends on it

if you think it's a good thing i can create a PR

**Comment by Lctrs** [comment]
With PHP 8.4 around the corner, I'm not inclined to force users to use a specific PHP version.

**Comment by xanscale** [comment]
i think we should simplify first run as possible, if we add last version of php extension most user can use out of the box.

if anyone need a specific version of php we can add info on first run txt on how to replace extension
