### ISSUE TITLE
JAVA_TOOL_OPTIONS env variable

### ISSUE THREAD

**Issue by rodrigopedra** [flathub/com.jetbrains.PhpStorm#23]
When starting PhpStorm it throws an event on the event log asking for not setting the `JAVA_TOOL_OPTIONS`, but I don't have this .env file

After some investigation I saw this variable is hardcoded by the launcher in:

https://github.com/flathub/com.jetbrains.PhpStorm/blob/e7645339628524a4518c303bd3be019bb4227403/phpstorm.sh#L17-L19

I wonder if removing it from this file, similar to what was done for IntelliJ Ultimate (link to the commit below) can solve this issue.

https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/commit/c2788a8f859cf991a7ca8986fc51c92cf380cedd

I can draft a PR if wanted.

**Comment by Lctrs** [comment]
If it works on Idea, it should works on phpstorm as well.

As I'm currently on vacations, I would appreciate that you submit a PR removing this and confirm that it works as expected. @flathubbot will provide you with some guidance on how to install the test build.

**Comment by rodrigopedra** [comment]
Hi @Lctrs , thanks for the PR. 

I was planning on working on this tomorrow as I was busy with my day job.

Sorry for not reaching back to you before and thanks again.
