### ISSUE TITLE
com.jetbrains.PhpStorm.flatpakref 404 not found

### ISSUE THREAD

**Issue by jlsjonas** [flathub/com.jetbrains.PhpStorm#28]
https://dl.flathub.org/repo/appstream/com.jetbrains.PhpStorm.flatpakref 404 not found
![image](https://user-images.githubusercontent.com/932193/99134538-70e71980-261e-11eb-8e27-91c27c40537f.png)

**Comment by bilelmoussaoui** [comment]
it works fine here. Please use the cli/a frontend to install the app instead of downloading the flatpakref manually.

**Comment by jlsjonas** [comment]
@bilelmoussaoui I used the install button on https://flathub.org/apps/details/com.jetbrains.PhpStorm after following the setup guideline

Missing docs?
