### ISSUE TITLE
Cannot find node or npm

### ISSUE THREAD

**Issue by petmi627** [flathub/com.jetbrains.PhpStorm#31]
Hello,

I run into a problem that PHPstorm cannot find node and npm, PHPstorm say that the $PATH variable is not correct, but I can run node and npm on the terminal.

Node is installed at /usr/bin/node.
```
$ whereis node
node: /usr/bin/node
$ whereis npm
npm: /usr/bin/npm /usr/share/npm
```

Do you have an idea what I can check or I can do more?

Thank you

**Comment by Lctrs** [comment]
Expected. Due to how flatpak works, flatpaked apps don't have access to host binaries.

You'll need to install one of `org.freedesktop.Sdk.Extension.node(10|12|14)`, though we only support `node10` at the moment. We'll make a PR soon to support the other versions.
