### ISSUE TITLE
PhpStorm terminal: can't get an access to host /usr/bin

### ISSUE THREAD

**Issue by asamofal** [flathub/com.jetbrains.PhpStorm#36]
Hi there! First of all thanks for this flatpak wrapper for PhpStorm.

I've faced with an issue: I can't get an access to my tools from `/usr/bin` path from host machine.

![image](https://user-images.githubusercontent.com/2729547/113279028-4d7dec00-92eb-11eb-80db-a8252685c5c3.png)

Is it a well-known flatpak restriction or it's possible to solve it somehow? 
Maybe it's possible to give some permissions to flatpak app and map `/usr/bin` path outside?

**Comment by Lctrs** [comment]
It's a well-known flatpak restriction, and it's possible to solve it somehow. Please see https://github.com/Lctrs/jetbrains-flatpak-wrapper/blob/master/first_run.txt.
