### ISSUE TITLE
flathub: Invalid rev

### ISSUE THREAD

**Issue by andypillip** [flathub/com.jetbrains.PhpStorm#52]
I’m not a flatpak power user or developer, forgive me if this error I get is due to my an issue on my local system, I wouldn’t know.

For two weeks now I’m getting the following error (translated from German by DeepL):

> Error: While fetching app/com.jetbrains.PhpStorm/x86_64/stable from remote source flathub: Invalid rev.
> Updates complete.
> Error: There were one or more errors

I found that there was a repair command in flatpak, so I tried it:

`$ flatpak repair`

And it provides the following message:

> [5/77] Verifying flathub:app/com.jetbrains.PhpStorm/x86_64/stable…
> Object missing: .commit
> Dry run: Deleting ref flathub:app/com.jetbrains.PhpStorm/x86_64/stable due to missing objects

I don’t get why it’s not deleting the ref, I did not start repair in dry mode.

Anyway, is there something that should be fixed in the repo?

Thanks.

**Comment by Lctrs** [comment]
That's not on the repo, that's on your computer locally. I don't know how to explain it clearly here, I'll contact you by mail so we can setup a call if you want.

**Comment by andypillip** [comment]
Thanks again for your help.

Uninstalling and reinstalling fixed it, settings are kept.
