### ISSUE TITLE
XDebug listener not working

### ISSUE THREAD

**Issue by TuningYourCode** [flathub/com.jetbrains.PhpStorm#6]
Today i tried to run the xdebug listener (phone with the bug on left side) but it does not open port 9000 as configured.
I also do not get any informations about errors if i open phpstorm from cli. Permission for networking is granted in flatpak.

Expected:
On click on that icon (activated) the ide should open port 9000 (or what ever is configured in settings).
Could be checked by `ss -n | grep 9000`.

Actual:
Port does not get opened - debugging is impossible.

**Comment by TuningYourCode** [comment]
nevermind, forgot to add -a to the ss command. Port looks to be open - have to figure out why the vm will not connect to it...

**Comment by Lctrs** [comment]
Have you tested that you can connect to it from the host ?

**Comment by TuningYourCode** [comment]
Well, sorry for reporting the issue :( The main problem at the end was that xdebug wasn't even installed in this specific vm (we are using vagrant & puppet to provision our development systems) as we normally do in our development maschines.

**Comment by Lctrs** [comment]
Okay. Thanks for following up :+1:
