### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by Lesik** [flathub/com.jetbrains.PhpStorm#71]
Hi,

with ARM machines becoming more and more popular to run Linux on, and the M1 Mac being a particularly powerful machine that is great for developing (if paired with [the right OS](https://asahilinux.org/) ;), it would be nice if the PhpStorm Flatpak would support ARM64.

From JetBrains' side, ARM64 support is already available. The ARM64 .tar.gz can be downloaded from the [official PhpStorm download page](https://www.jetbrains.com/phpstorm/download/#section=linux) ([current direkt link to .tar.gz file](https://download.jetbrains.com/webide/PhpStorm-2022.3.3-aarch64)).

The IntelliJ IDEA Community Edition Flatpak [recently added support for ARM64](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/commit/bde8594dceb88854bb8776421cff0939e5927676) (I tested it and it works great), and from a first glance, it seems like we can pretty much copy what they did. Though it is to note that they had to (temporarily?) [revert the changes](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/commit/a156432173fd1a39bb57ec30cf64442d385861e0) because of a bug with the Flathub auto-updater (perhaps @x80486 could provide more info on why they had to do that and what the solution was in the end?).

**Comment by x80486** [comment]
What's happening is that somehow the `Flathub` auto-updater is not really recognizing the other install, so it's applying back the same URL and hash for both. I think it might be easy to fix based [on the changes](https://github.com/flathub/flatpak-external-data-checker/pull/341/files) I saw for this, but I couldn't see what was causing the issue.

**Comment by Lctrs** [comment]
Let's wait for a fix to fedc before going further with this.

**Comment by Lesik** [comment]
@Lctrs I respect your decision to wait before fedc is fixed, but I would just like to add that there are only about three PhpStorm releases per year, so manually adjusting the hashes wouldn't be a huge hassle (I offer to take care of it) compared to the benefit of having an ARM64 Flatpak available on Flathub for all users.

@x80486 I couldn't find an issue/ticket in the fedc repo regarding the bug you faced - could you create an issue or should I?

**Comment by Lctrs** [comment]
There are 3 major/minor releases per year, but there are more patch releases than that. I don't want to have to watch for releases everyday and do the updates to the repo manually (I had my shares of human errors with this process in the past).

if having flatpaked jetbrains products compatible with ARM64 is that critical for you, I suggest you work on fixing the jetbrains checker on fedc.
