### ISSUE TITLE
Crash when opening any markdown window or anything else that spawns the internal Browser view

### ISSUE THREAD

**Issue by waffshappen** [flathub/com.jetbrains.PhpStorm#75]
Just like reported in https://youtrack.jetbrains.com/issue/IDEA-313202 any attempt to launch any project that last had a readme.md open or if any addon wants to show a "i was updated!" message the entire IDE grinds to a halt, then hard-crashes.

Disabling the sandbox from the splashscreen in the registry (ide.browser.jcef.sandbox.enable) works but doesnt sound like the ideal workaround.

Fedora 38, latest flatpak.

**Comment by Lctrs** [comment]
May you test #76 ?

**Comment by waffshappen** [comment]
> May you test #76 ?

Can confirm its fixed.

**Comment by da-anda** [comment]
unfortunately latest flatpack on Fedora39 crashes as soon as I open any file that has a preview window, like any markdown (.md) file. I tried a couple things already, but couldn't get it working. Any ideas/suggestions?

**Comment by rteitge** [comment]
I have the same problem.

> unfortunately latest flatpack on Fedora39 crashes as soon as I open any file that has a preview window, like any markdown (.md) file. I tried a couple things already, but couldn't get it working. Any ideas/suggestions?
