### ISSUE TITLE
System update causes PhpStorm to crash on startup

### ISSUE THREAD

**Issue by Girgias** [flathub/com.jetbrains.PhpStorm#85]
Not really sure why this happens, but the log output is as follows:

```
[girgias@fedora ~]$ flatpak run com.jetbrains.PhpStorm
phpstorm-wrapper: Setting up NPM packages
phpstorm-wrapper: Setting up Cargo packages
phpstorm-wrapper: Setting up Python packages
phpstorm-wrapper: Setting up Ruby packages
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

Start Failed
Cannot connect to already running IDE instance.
Exception: Process 2 is still running
Gtk-Message: 19:09:47.279: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:09:47.280: Failed to load module "pk-gtk-module"
Gtk-Message: 19:09:47.280: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:09:47.280: Failed to load module "pk-gtk-module"
```

**Comment by vbsessa** [comment]
For me a temporary fix that worked was remove the .lock file.

```bash
rm $HOME/.var/app/com.jetbrains.PhpStorm/config/JetBrains/PhpStorm2023.2/.lock
```

Hope it helps.

**Comment by Girgias** [comment]
Thank you, this does help.

I think I figured out the issue, is that for some reason the flathub version of PhpStorm crashes when trying to opean a markdown file, which happens when loading a new project as it will open the README file.

**Comment by biertz** [comment]
> Thank you, this does help.
> 
> I think I figured out the issue, is that for some reason the flathub version of PhpStorm crashes when trying to opean a markdown file, which happens when loading a new project as it will open the README file.

@Girgias I can confirm this.  Running Phpstorm with `flatpak run` and opening a Markdown file prints the following error to the console:

```
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/phpstorm/jbr/lib/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by mneon512** [comment]
@biertz, disable the markdown plugin. Tomorrow I'll try to get a fix from another repository and post here.

**Comment by mneon512** [comment]
Temporary solution to the problem:
https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/issues/124?ysclid=lnnuppdodd727417302#issuecomment-1494989255
